### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by chegewara** [asterics/esp32_mouse_keyboard#10]
If i may suggest something. Now report map and all application functions related to this definition (mouse, joystick and keyboard) are based on preprocessor define :
https://github.com/asterics/esp32_mouse_keyboard/blob/newBLE/components/nkolban_BLE/HID_kbdmousejoystick.cpp#L53

It is possible, maybe for test purpose only or maybe for finale product, to use dip switch and based on GPIO level on esp32 reboot to have different devices available. This will speed up and help with windows drivers compatibility. No need to recompile application to test which report map part is broken.

**Comment by benjaminaigner** [comment]
Hi,

because this is a testing repo for BLE source, of course we can talk about suggestions / changes.
I think this is a good proposal, maybe this way:

- Use 3 GPIOs with Pull Ups, one for each type of HID interface (keyboard/mouse/joystick)
- If the GPIO is left floating or pulled up, the corresponding interface is active
- If the GPIO is connected to GND, it will be disabled.

For now I will have all interfaces active, until I married the serial API (this repo was originally intended to replace an Adafruit EZKey) with your BLE implementation.

**Comment by chegewara** [comment]
This is your code, your application and your repo. Even if part of it is my code i have nothing to do or say about it because my code is public domain or apache ( Kolban's repo is apache) licensed. My siggestion is only to help you and if you feel its not what you want im fine with that. 
Another thing is that i have windows 10 PRO
